name: CI Checks 

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci-checks:
    name: CI Checks 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
        id: setup-node
      - name: Get Node Version
        run: echo "::set-output name=version::$(node -v)"
        id: node-version
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: ESlint
        run: yarn eslint -f github .
      - name: Unit tests
        run: yarn test --reporters=github-actions
