openapi: 3.0.3
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /:
    get:
      description: the root
      responses:
        default:
          description: root
          content:
            text/plain:
              schema:
                type: string
              examples:
                root:
                  value: This is the root.

  /count:
    get:
      description: outputs the number of time each URL was visited
      responses:
        default:
          description: Successful response
          content:
            application/json:
              schema:
                type: string
              examples:
                no visits:
                  value: You have not visited anyone yet
  /hello/kitty:
    get:
      description: HTML with a hello kitty image
      responses:
        default:
          description: Successful response
          content:
            application/json:
              schema:
                type: string
              examples:
                hello kitty:
                  value: >-
                    <img
                    src="https://upload.wikimedia.org/wikipedia/en/0/05/Hello_kitty_character_portrait.png">
  /hello/{name}:
    get:
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: says hello to the name
      description: says hello to someone
      responses:
        default:
          description: Successful response
          headers:
            x-test:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: string
                example: an example string
              examples:
                hello-example1:
                  value: Hello, example1
                hello-example2:
                  value: Hello, example2
  /path-one:
    get:
      responses:
        "200":
          description: test
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recursive"
        "400":
          $ref: "#/components/responses/BadRequest"

components:
  responses:
    BadRequest:
      description: The request is malformed and so cannot be processed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      title: Error
      description: A generic error message suitable for 4xx and 5xx responses
      type: object
      properties:
        code:
          type: string
          description: A machine readable error code
        message:
          type: string
          description: A detailed description of the error
      required:
        - message
    Recursive:
      oneOf:
        - { $ref: "#/components/schemas/Recursive" }

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
