import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import nodePath from "node:path";

import createDebug from "debug";

import { ensureDirectoryExists } from "../util/ensure-directory-exists.js";
import { OperationCoder } from "./operation-coder.js";
import { type SecurityScheme } from "./operation-type-coder.js";
import { pruneRoutes } from "./prune.js";
import { Repository } from "./repository.js";
import { Specification } from "./specification.js";

const debug = createDebug("counterfact:typescript-generator:generate");

interface GenerateOptions {
  prune?: boolean;
  routes?: boolean;
  types?: boolean;
}

async function buildCacheDirectory(destination: string): Promise<void> {
  const gitignorePath = nodePath.join(destination, ".gitignore");
  const cacheReadmePath = nodePath.join(destination, ".cache", "README.md");

  debug("ensuring the directory containing .gitgnore exists");

  await ensureDirectoryExists(gitignorePath);

  debug("creating the .gitignore file if it doesn't already exist");

  if (!existsSync(gitignorePath)) {
    await fs.writeFile(gitignorePath, ".cache\n", "utf8");
  }

  debug("creating the .cache/README.md file");

  ensureDirectoryExists(cacheReadmePath);
  await fs.writeFile(
    cacheReadmePath,
    "This directory contains compiled JS files from the paths directory. Do not edit these files directly.\n",
    "utf8",
  );
}

async function getPathsFromSpecification(
  specification: Specification,
): Promise<ReturnType<Specification["getRequirement"]>> {
  try {
    return specification.getRequirement("#/paths") ?? new Set<never>();
  } catch (error) {
    process.stderr.write(
      `Could not find #/paths in the specification.\n${error as string}\n`,
    );

    return undefined as unknown as ReturnType<Specification["getRequirement"]>;
  }
}

export async function generate(
  source: string,
  destination: string,
  generateOptions: GenerateOptions,
  repository = new Repository(),
): Promise<void> {
  debug("generating code from %s to %s", source, destination);

  debug("initializing the .cache directory");
  await buildCacheDirectory(destination);
  debug("done initializing the .cache directory");

  debug("creating specification from %s", source);

  const specification = await Specification.fromFile(source);

  debug("created specification: $o", specification);

  debug("reading the #/paths from the specification");

  const paths = await getPathsFromSpecification(specification);

  debug("got %i paths", paths?.map?.length ?? 0);

  if (generateOptions.prune && generateOptions.routes) {
    debug("pruning defunct route files");
    await pruneRoutes(
      destination,
      paths.map((_v, key) => key),
    );
    debug("done pruning");
  }

  const securityRequirement = specification.getRequirement(
    "#/components/securitySchemes",
  );

  const securitySchemes = Object.values(
    (securityRequirement?.data as Record<string, unknown>) ?? {},
  ) as SecurityScheme[];

  paths.forEach((pathDefinition, key: string) => {
    debug("processing path %s", key);

    const path = key === "/" ? "/index" : key;
    pathDefinition.forEach((operation, requestMethod: string) => {
      repository
        .get(`routes${path}.ts`)
        .export(new OperationCoder(operation, requestMethod, securitySchemes));
    });
  });

  debug("telling the repository to write the files to %s", destination);

  await repository.writeFiles(destination, generateOptions);

  debug("finished writing the files");

  if (generateOptions.types) {
    await writeApplyContextType(destination);
  }
}

const APPLY_CONTEXT_TYPE = `// This file is generated by Counterfact. Do not edit manually.

export interface ApplyContext {
  /** Root context, same as loadContext("/") */
  context: Record<string, unknown>;
  /** Load a context object for a specific path */
  loadContext: (path: string) => Record<string, unknown>;
  /** Named route builders stored in the REPL execution context */
  routes: Record<string, unknown>;
  /** Create a new route builder for a given path */
  route: (path: string) => unknown;
}
`;

async function writeApplyContextType(destination: string): Promise<void> {
  const typesDir = nodePath.join(destination, "types");
  const filePath = nodePath.join(typesDir, "apply-context.ts");

  await fs.mkdir(typesDir, { recursive: true });
  await fs.writeFile(filePath, APPLY_CONTEXT_TYPE, "utf8");
}
